import unittest
from teeny.runner import run_code
from teeny.value import makeObject, Error, Nil

class TestArithmetic(unittest.TestCase):
    def test_basic_operator(self):
        self.assertEqual(makeObject(run_code('1 + 2', False, False, False)), 3)
        self.assertEqual(makeObject(run_code('1 - 2', False, False, False)), -1)
        self.assertEqual(makeObject(run_code('2 * 3', False, False, False)), 6)
        self.assertEqual(makeObject(run_code('5 / 2', False, False, False)), 2.5)
        self.assertEqual(makeObject(run_code('5 % 2', False, False, False)), 1)
        self.assertEqual(makeObject(run_code('-1', False, False, False)), -1)
        self.assertEqual(makeObject(run_code('-1 + 2', False, False, False)), 1)
        self.assertEqual(makeObject(run_code('+1', False, False, False)), 1)
        self.assertEqual(makeObject(run_code('2 * -3', False, False, False)), -6)
        self.assertEqual(makeObject(run_code('!1', False, False, False)), 0)
        self.assertEqual(makeObject(run_code('1 && 0', False, False, False)), 0)
        self.assertEqual(makeObject(run_code('0 && 1', False, False, False)), 0)
        self.assertEqual(makeObject(run_code('1 && 1', False, False, False)), 1)
        self.assertEqual(makeObject(run_code('a := 1; 0 && (a = 2); a', False, False, False)), 1)
        self.assertEqual(makeObject(run_code('1 || 0', False, False, False)), 1)
        self.assertEqual(makeObject(run_code('0 || 0', False, False, False)), 0)
        self.assertEqual(makeObject(run_code('0 || 1', False, False, False)), 1)
        self.assertEqual(makeObject(run_code('a := 1; 1 || (a = 2); a', False, False, False)), 1)
        self.assertEqual(run_code('1 / 0', False, False, False), Error(typ = "Runtime Error", value = "divide by zero"))
        self.assertEqual(makeObject(run_code('1 == 0', False, False, False)), 0)
        self.assertEqual(makeObject(run_code('1 == 1', False, False, False)), 1)
        self.assertEqual(makeObject(run_code('1 != 0', False, False, False)), 1)
        self.assertEqual(makeObject(run_code('1 != 1', False, False, False)), 0)
        self.assertEqual(makeObject(run_code('1 < 0', False, False, False)), 0)
        self.assertEqual(makeObject(run_code('1 > 0', False, False, False)), 1)
        self.assertEqual(makeObject(run_code('1 <= 1', False, False, False)), 1)
        self.assertEqual(makeObject(run_code('1 >= 0', False, False, False)), 1)
        self.assertEqual(makeObject(run_code('3!', False, False, False)), 6)
        self.assertEqual(run_code('1 + "a"', False, False, False), Error(typ = "Runtime Error", value = "add a non-Number to a Number"))
        self.assertEqual(run_code('1 - "a"', False, False, False), Error(typ = "Runtime Error", value = "minus a non-Number from a Number"))
        self.assertEqual(run_code('1 * "a"', False, False, False), Error(typ = "Runtime Error", value = "multiply a non-Number with a Number"))
        self.assertEqual(run_code('1 / "a"', False, False, False), Error(typ = "Runtime Error", value = "divide a non-Number from a Number"))
        self.assertEqual(run_code('1 < "a"', False, False, False), Error(typ = "Runtime Error", value = "compare between non-Number and Number"))
        self.assertEqual(run_code('1 > "a"', False, False, False), Error(typ = "Runtime Error", value = "compare between non-Number and Number"))
        self.assertEqual(run_code('1 <= "a"', False, False, False), Error(typ = "Runtime Error", value = "compare between non-Number and Number"))
        self.assertEqual(run_code('1 >= "a"', False, False, False), Error(typ = "Runtime Error", value = "compare between non-Number and Number"))
        self.assertEqual(run_code('"a" + 1', False, False, False), Error(typ = "Runtime Error", value = "add a non-String to a String"))
        self.assertEqual(run_code('"a" > 1', False, False, False), Error(typ = "Runtime Error", value = "compare between non-String and String"))
        self.assertEqual(run_code('"a" < 1', False, False, False), Error(typ = "Runtime Error", value = "compare between non-String and String"))
        self.assertEqual(run_code('"a" >= 1', False, False, False), Error(typ = "Runtime Error", value = "compare between non-String and String"))
        self.assertEqual(run_code('"a" <= 1', False, False, False), Error(typ = "Runtime Error", value = "compare between non-String and String"))
        self.assertEqual(run_code('[1, 2] + 1', False, False, False), Error(typ = "Runtime Error", value = "add a non-Table to a Table"))
        self.assertEqual(run_code('nil', False, False, False), Nil())
        self.assertEqual(makeObject(run_code('a := 1', False, False, False)), 1)
        self.assertEqual(run_code('b = 1', False, False, False), Error(typ = "Runtime Error", value = "assign to non-existing variable"))
        self.assertEqual(run_code('c', False, False, False), Error(typ = "Runtime Error", value = "read from non-existing variable"))
        self.assertEqual(makeObject(run_code('a := 1; a ?= 2', False, False, False)), 1)
        self.assertEqual(makeObject(run_code('a := 1; b := nil; [a, b] ?= [2, 3]', False, False, False)), [1, 3])
        self.assertEqual(makeObject(run_code('[a, _] := [1, 2]', False, False, False)), [1, None])
        self.assertEqual(makeObject(run_code('[a, _] := [1, 2]', False, False, False)), [1, None])
        self.assertEqual(makeObject(run_code('[a, b] := [b: 1, a: 2]; [a, b]', False, False, False)), [2, 1])
        self.assertEqual(makeObject(run_code('[a: c, b] := [b: 1, a: 2]; [c, b]', False, False, False)), [2, 1])
        self.assertEqual(makeObject(run_code('1..3', False, False, False)), [1, 2, 3])
        self.assertEqual(run_code('1.."a"', False, False, False), Error(typ = 'Runtime Error', value = 'non-Number in range operator'))
        self.assertEqual(run_code('"a"..2', False, False, False), Error(typ = 'Runtime Error', value = 'non-Number in range operator'))
        self.assertEqual(makeObject(run_code('1 ?? 2', False, False, False)), 1)
        self.assertEqual(makeObject(run_code('nil ?? 2', False, False, False)), 2)
    def test_operator_precedence(self):
        self.assertEqual(makeObject(run_code('1 + 2 * 3', False, False, False)), 7)
        self.assertEqual(makeObject(run_code('(1 + 2) * 3', False, False, False)), 9)
        self.assertEqual(makeObject(run_code('10 - 4 / 2', False, False, False)), 8)
        self.assertEqual(makeObject(run_code('10 - (4 / 2)', False, False, False)), 8)
        self.assertEqual(makeObject(run_code('10 - (4 / (2 + 2))', False, False, False)), 9)

if __name__ == "__main__":
    unittest.main()